services:
  # Configuration Server
  config-server:
    build:
      context: ./ConfigurationServer
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - shop-network

  # Configuration Client
  config-client:
    build:
      context: ./ConfigurationClient
      dockerfile: Dockerfile
    container_name: config-client
    ports:
      - "8889:8889"
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    networks:
      - shop-network

  #Catalog
  catalog:
    build:
      context: ./Catalog
      dockerfile: Dockerfile
    container_name: catalog
    ports:
      - "8082:8082"
    depends_on:
      - config-client
    environment:
      - EUREKA_URI=http://shop-eureka-server:8761/eureka
    networks:
      - shop-network

  # Order
  order:
    build:
      context: ./Order
      dockerfile: Dockerfile
    container_name: order
    ports:
      - "8083:8083"
    depends_on:
      - config-client
      - catalog
    environment:
      - EUREKA_URI=http://shop-eureka-server:8761/eureka
    networks:
      - shop-network

  # Eureka Server
  shop-eureka-server:
    build:
      context: ./ShopEurekaServer
      dockerfile: Dockerfile
    container_name: shop-eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - order
      - catalog
    networks:
      - shop-network

  # Shop Gateway
  shop-gateway:
    build:
      context: ./ShopGateway
      dockerfile: Dockerfile
    container_name: shop-gateway
    ports:
      - "9000:9000"
    depends_on:
      - shop-eureka-server
    environment:
      - EUREKA_URI=http://shop-eureka-server:8761/eureka
    networks:
      - shop-network

# Network
networks:
  shop-network:
    driver: bridge
